pages:
  tags:
    - pages
  script:
  - conda activate ci
  - pip install -r requirements.txt
  - cd docs
  - pip install -r requirements-docs.txt
  - make clean
  - make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
