## Learnable hyper-parameters 
---
  lr: {range: [1e-6, 1e-2]}
  batch_size: {i_range: [100, 400], step: 100}
  latent_distribution: [vmf, gaussian, logistic_gaussian]
  optimizer: [adam]
  n_latent: {i_range: [20]}
  enc_hidden_dim: {i_range: [50, 400], step: 50}
  kappa: {range: [1.0, 100.0]}   ## conditional on latent_distribution==vmf
  ## target_sparsity: {range: [0.0, 0.2]}
  ## coherence_regularizer_penalty: {range: [0.0, 0.2] }
  ## embedding_source: [none, glove.42B.300d, glove.6B.100d, glove.6B.200d, glove.6B.300d, glove.6B.50d, glove.840B.300d, glove.twitter.27B.100d]
  embedding_source: [glove:glove.42B.300d, glove:glove.6B.200d, fasttext:wiki.en]
  ## fixed_embedding: [True, False]
  ## embedding_size: {i_range: [50, 400], step: 50}